<?php
use Illuminate\Database\Seeder;
use Illuminate\Database\Eloquent\Model;
use App\User;

class EspecialidadesTableSeeder extends Seeder {
    public function run()
    {
        DB::table('especialidades')->delete();
        DB::statement("insert into especialidades (nombre) values 
				('CLINICA MEDICA'),
				('MEDICINA GENERAL y/o MEDICINA DE FAMILIA'),
				('ALERGIA E INMUNOLOGIA'),
				('CARDIOLOGIA'),
				('ANGIOLOGIA GENERAL Y HEMODINAMIA'),
				('DERMATOLOGIA'),
				('ENDOCRINOLOGIA'),
				('FARMACOLOGIA CLINICA'),
				('FISIATRIA (MEDICINA FISICA Y REHABILITACION)'),  
				('GASTROENTEROLOGIA'),
				('GENETICA MEDICA'),
				('GERIATRIA'),
				('HEMATOLOGIA'),
				('INFECTOLOGIA'),
				('NEFROLOGIA'),
				('NEUMONOLOGIA'),
				('NEUROLOGIA'),
				('NUTRICION'),
				('ONCOLOGIA'),
				('REUMATOLOGIA'),
				('TERAPIA INTENSIVA'),
				('CIRUGIA GENERAL'),
				('CIRUGIA CARDIOVASCULAR'),
				('CIRUGIA DE CABEZA Y CUELLO'),
				('CIRUGIA DE TORAX (CIRUGIA TORACICA)'),  
				('CIRUGIA INFANTIL (CIRUGIA PEDIATRICA)'),  
				('CIRUGIA PLASTICA Y REPARADORA'),
				('CIRUGIA VASCULAR PERIFERICA'),
				('COLOPROCTOLOGIA'),
				('GINECOLOGIA'),
				('NEUROCIRUGIA'),
				('OBSTETRICIA'),
				('OFTALMOLOGIA'),
				('ORTOPEDIA Y TRAUMATOLOGIA'),
				('OTORRINOLARINGOLOGIA'),
				('TOCOGINECOLOGIA'),
				('UROLOGIA'),
				('PEDIATRIA'),
				('CARDIOLOGO INFANTIL'),
				('ENDOCRINOLOGO INFANTIL'),
				('GASTROENTEROLOGO INFANTIL'),
				('HEMATOLOGO INFANTIL'),
				('INFECTOLOGO INFANTIL'),
				('NEFROLOGO INFANTIL'),
				('NEONATOLOGIA'),
				('NEUMONOLOGO INFANTIL'),
				('NEUROLOGO INFANTIL'),
				('ONCOLOGO INFANTIL'),
				('REUMATOLOGO INFANTIL'),
				('TERAPISTA INTENSIVO INFANTIL'),
				('PSIQUIATRIA'),
				('PSIQUIATRIA INFANTO JUVENIL'),
				('ANATOMIA PATOLOGICA'),
				('ANESTESIOLOGIA'),
				('DIAGNOSTICO POR IMAGENES'),
				('HEMOTERAPIA E INMUNOHEMATOLOGIA'),
				('MEDICINA DEL DEPORTE'),
				('MEDICINA DEL TRABAJO'),
				('MEDICINA LEGAL'),
				('MEDICINA NUCLEAR'),
				('RADIOTERAPIA O TERAPIA RADIANTE'),
				('TOXICOLOGIA')
        	");

    }
}